### ISSUE TITLE
how to use vc2017 to complie this to a windows app?

### ISSUE THREAD

**Issue by jinyugang** [loathingKernel/Qutefan#1]
Hi Buddy. I am trying to use vc2017 to complie and package this to a windows app. but it can not work... what's your suggestion to make it?

**Comment by loathingKernel** [comment]
You have to use Qt, then you can build it through QtCreator or QMake directly. Qt has a few different versions for both VC and MingW. As it is now, you will need a static version of Qt to package it into a single exe.
